# Server configuration
server:
  addr: "0.0.0.0"
  port: "8081"

# Database configuration
database:
  dsn: "utopia:45e8658a3ed833-f960487b8416c07D@tcp(mysql4a07f5fe11f0.rds.ivolces.com:3306)/utopia2?parseTime=true"

# JWT configuration
jwt:
  secret_key: "a-very-secret-key"
  token_ttl: 3600 # 1 hour in seconds

# FRP (tunnel) configuration
frp:
  bind_port: 7000
  token: "utopia-auth-token"
  dashboard_addr: "0.0.0.0"
  dashboard_port: 7500
  dashboard_user: "admin"
  dashboard_pwd: "admin"
  agent_token: "a_very_secret_agent_api_token"